[package]
name = "ghost_link"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

# Internal dependencies
ghost_policy = { path = "../ghost_policy" }
